spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/oauth_client?serverTimezone=UTC
application:
    name: authorization-server


config:
  clientid: kailash
  clientSecret: 1234567890
  publicKey: -----BEGIN PUBLIC KEY-----
          MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrFZtP4GYt820lpGyANB4Fr6hj
          2xnYyxNMBgh0kaa6fvaplBYmELo/2Zvn6W6Ryw7DaaGq/kJEoS3gBIYw4KLeANOV
          bk3nvIGiDGuNQjfRoslUoVcU04f/Z7YOcZecUwXM2ZgssPyZjr0Qu37gydcjrQzt
          4CsQRYgvUnAmOUMukQIDAQAB
          -----END PUBLIC KEY-----
  privateKey: -----BEGIN RSA PRIVATE KEY-----
         MIICXQIBAAKBgQCrFZtP4GYt820lpGyANB4Fr6hj2xnYyxNMBgh0kaa6fvaplBYm
         ELo/2Zvn6W6Ryw7DaaGq/kJEoS3gBIYw4KLeANOVbk3nvIGiDGuNQjfRoslUoVcU
          04f/Z7YOcZecUwXM2ZgssPyZjr0Qu37gydcjrQzt4CsQRYgvUnAmOUMukQIDAQAB
          AoGAXM2lqBiTlM19IXQlnw2mU3NLpo8NYDoYR57mK0Vu6a9BYg+ATDm6rjP+jDhl
          0BQT+BBur/CoRc4gsmoB2LWh4mPzwrnT6TM8DxsJBO8wrfikGS1z19FOzIE8yHFr
          ltJ7Q7vLeIxi1igx2/yfiWb+IKPwRwdWv3H0VA88daCjXhkCQQDW8NfBoryYUlm2
          L/TnxxBbYprkbQGhBfBf2AnF0RD+6YnD1Ue9SFCdGxskLxm7ls6oP1RvSjE2NSvs
          IOyc1hFDAkEAy8QS2jQ2gsi1EOKTNc3MsL0j7dEqEv3Rj8lTE0x4En49L9XJocY2
          Oll4tKcGtbWrfUkmOcbprwSfKcI4heEpmwJBAMK6Y93r/4zIXrpt7CTn9eu1A7sa
          /rTRWpqacRAkfo9TKRqgaWQU1ePfoNFBUsDeuc83wNkqkDcaKPa+RV85mV0CQQCl
          0+kfyXQ/VUX9+tag595YS2UtCpc6I3Rjlw1T3FyveCslfc/9JwlEzUGti2yrfrCU
          Ym6IgLf25kT9wAEt+0NXAkBBQ9j15AwLPKSRLxL/FpfHRddYhgpU3rmTH7LRG1OA
          M+o+0vmogzgxkZ2lAKMYKDILBINV9UKrjO1GK+jg+jUS
          -----END RSA PRIVATE KEY-----
